/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.vista;

import com.sv.udb.controlador.EquiposCtrl;
import com.sv.udb.controlador.JugadoresCtrl;
import com.sv.udb.controlador.PartidosCtrl;
import com.sv.udb.modelo.Equipos;
import com.sv.udb.modelo.Jugadores;
import com.sv.udb.modelo.Partidos;
import com.sv.udb.recursos.Conexion;
import java.sql.Connection;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Lira
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        llenarCombobox();
    }
    
    //Metodo para consultar 
    public void Mostrar(){
          try {
            DefaultTableModel model = (DefaultTableModel)this.tblEquipos.getModel();
            while (model.getRowCount()>0){model.removeRow(0);}//Limpiar modelo
            for(Equipos temp : new EquiposCtrl().consTodo())
            {
                model.addRow(new Object[]{temp, temp.getDescEqui()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }    
    }
    
    
     public void MostrarJuga(){
          try {
            DefaultTableModel model = (DefaultTableModel)this.tblJugadores.getModel();
            while (model.getRowCount()>0){model.removeRow(0);}//Limpiar modelo
            for(Jugadores temp : new JugadoresCtrl().constTodo())
            {
                model.addRow(new Object[]{temp.getCodiEqui(),temp,temp.getEdadJuga(),temp.getAltuJuga(), temp.getPesoJuga()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }    
    }
     
     public void MostrarPart(){
          try {
            DefaultTableModel model = (DefaultTableModel)this.tblPartidos.getModel();
            while (model.getRowCount()>0){model.removeRow(0);}//Limpiar modelo
            for(Partidos temp : new PartidosCtrl().constTodo())
            {
                model.addRow(new Object[]{temp.getCodiEqui1(),temp.getCodiEqui2(),temp.getGoleEqui1(),temp.getGoleEqui2(), temp.getFechHora(), temp.getLugar()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }    
    }
     
     private void llenarCombobox(){
     DefaultComboBoxModel<Equipos>modeEqui = new DefaultComboBoxModel<>();
     for (Equipos temp : new EquiposCtrl().consTodo())
     {
         modeEqui.addElement(temp);
     }
     this.cmbCodiEqui.setModel((ComboBoxModel)modeEqui);
     this.cmbCodiEquiPart1.setModel((ComboBoxModel)modeEqui);
     this.cmbCodiEquiPart2.setModel((ComboBoxModel)modeEqui);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodi = new javax.swing.JTextField();
        txtNomb = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEquipos = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtCodi1 = new javax.swing.JTextField();
        txtNombJuga = new javax.swing.JTextField();
        btnConsultar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAltu = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        cmbCodiEqui = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMarcEqui1 = new javax.swing.JTextField();
        txtCodiPart = new javax.swing.JTextField();
        btnConsultarPart = new javax.swing.JButton();
        btnEliminarPart = new javax.swing.JButton();
        btnNuevoPart = new javax.swing.JButton();
        btnModificarPart = new javax.swing.JButton();
        btnGuardarPart = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMarcEqui2 = new javax.swing.JTextField();
        txtFechHora = new javax.swing.JTextField();
        cmbCodiEquiPart1 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPartidos = new javax.swing.JTable();
        cmbCodiEquiPart2 = new javax.swing.JComboBox();
        txtLuga = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripción:");

        txtCodi.setEditable(false);
        txtCodi.setText("1");
        txtCodi.setToolTipText("");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        tblEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEquipos);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtNomb)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Equipos", jPanel1);

        jLabel4.setText("Codigo:");

        jLabel5.setText("Codigo Equipo:");

        jLabel6.setText("Nombre:");

        txtCodi1.setEditable(false);
        txtCodi1.setText("1");
        txtCodi1.setToolTipText("");

        txtNombJuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombJugaActionPerformed(evt);
            }
        });

        btnConsultar1.setText("Consultar");
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnNuevo1.setText("Nuevo");
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Edad:");

        jLabel8.setText("Altura");

        jLabel9.setText("Peso");

        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Equipo", "Nombre", "Edad", "Altura", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJugadoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblJugadores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombJuga)
                            .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtCodi1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltu, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(cmbCodiEqui, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCodi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmbCodiEqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(txtAltu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jugadores", jPanel2);

        jLabel10.setText("Codigo:");

        jLabel11.setText("Equipo 1:");

        jLabel12.setText("Equipo 2:");

        txtMarcEqui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcEqui1ActionPerformed(evt);
            }
        });

        txtCodiPart.setEditable(false);
        txtCodiPart.setText("1");
        txtCodiPart.setToolTipText("");

        btnConsultarPart.setText("Consultar");
        btnConsultarPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPartActionPerformed(evt);
            }
        });

        btnEliminarPart.setText("Eliminar");
        btnEliminarPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPartActionPerformed(evt);
            }
        });

        btnNuevoPart.setText("Nuevo");
        btnNuevoPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPartActionPerformed(evt);
            }
        });

        btnModificarPart.setText("Modificar");
        btnModificarPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPartActionPerformed(evt);
            }
        });

        btnGuardarPart.setText("Guardar");
        btnGuardarPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPartActionPerformed(evt);
            }
        });

        jLabel13.setText("Goles Equipo 1:");

        jLabel14.setText("Goles Equipo 2:");

        jLabel15.setText("Fecha y Hora:");

        cmbCodiEquiPart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodiEquiPart1ActionPerformed(evt);
            }
        });

        tblPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipo 1", "Equipo 2", "Goles Equipo 1", "Goles Equipo 2", "Fecha y Hora", "Lugar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPartidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblPartidosMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tblPartidos);

        jLabel16.setText("Lugar:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMarcEqui1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txtCodiPart, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarcEqui2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txtFechHora, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(cmbCodiEquiPart1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbCodiEquiPart2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnGuardarPart, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnConsultarPart, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnModificarPart, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminarPart, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtLuga))
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnNuevoPart, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtCodiPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cmbCodiEquiPart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCodiEquiPart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(txtMarcEqui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addComponent(txtMarcEqui2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtFechHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtLuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarPart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarPart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarPart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarPart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnNuevoPart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Partidos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       btnGuardar.setEnabled(true);
       btnConsultar.setEnabled(true);
       btnModificar.setEnabled(false);
       btnEliminar.setEnabled(false);
       btnNuevo.setEnabled(false);
       
       
       btnGuardar1.setEnabled(true);
       btnConsultar1.setEnabled(true);
       btnModificar1.setEnabled(false);
       btnEliminar1.setEnabled(false);
       btnNuevo1.setEnabled(false);
       
       btnGuardarPart.setEnabled(true);
       btnConsultarPart.setEnabled(true);
       btnModificarPart.setEnabled(false);
       btnEliminarPart.setEnabled(false);
       btnNuevoPart.setEnabled(false);
       
       
    }//GEN-LAST:event_formWindowOpened

    private void tblJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJugadoresMouseClicked
        try{
            int fila = this.tblJugadores.getSelectedRow();
            if(fila >= 0)
            {
                Jugadores obje = (Jugadores)this.tblJugadores.getValueAt(fila, 1);
                this.txtCodi1.setText(String.valueOf(obje.getCodiJuga()));
                this.cmbCodiEqui.setEditable(true);
                this.cmbCodiEqui.setSelectedItem((Equipos)new EquiposCtrl().concmb(obje.getCodiEqui()));
                this.cmbCodiEqui.setEditable(false);
                this.txtNombJuga.setText(obje.getNombJuga());
                this.txtEdad.setText(String.valueOf(obje.getEdadJuga()));
                this.txtAltu.setText(String.valueOf(obje.getAltuJuga()));
                this.txtPeso.setText(String.valueOf(obje.getPesoJuga()));
            }}
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Error"+ ex.getMessage());
            }
    }//GEN-LAST:event_tblJugadoresMouseClicked

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        try {
            if(txtNombJuga.getText().length()!=0 && txtEdad.getText().length()!=0 && txtAltu.getText().length()!=0 && txtPeso.getText().length()!=0)
            {
                // this.cmbCodiEqui.setSelectedIndex(obje.getCodiEqui());
                Equipos objeEqui = (Equipos) this.cmbCodiEqui.getSelectedItem();
                Jugadores obje = new Jugadores();
                obje.setCodiJuga(Integer.parseInt(this.txtCodi1.getText()));
                obje.setCodiEqui(objeEqui.getCodiEqui());
                obje.setNombJuga(this.txtNombJuga.getText());
                obje.setEdadJuga(Integer.parseInt(this.txtEdad.getText()));
                obje.setAltuJuga(Double.parseDouble(this.txtAltu.getText()));
                obje.setPesoJuga(Double.parseDouble(this.txtPeso.getText()));

                if(new JugadoresCtrl().guar(obje))
                {
                    JOptionPane.showMessageDialog(this, "Datos guardados");
                    txtCodi1.setText("1");
                    txtNombJuga.setText("");
                    txtEdad.setText("");
                    txtAltu.setText("");
                    txtPeso.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No deje campos vacios");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        try
        {
            Equipos objeEqui = (Equipos) this.cmbCodiEqui.getSelectedItem();
            Jugadores obje = new Jugadores();
            obje.setCodiJuga(Integer.parseInt(this.txtCodi1.getText()));
            obje.setCodiEqui(objeEqui.getCodiEqui());
            //obje.setCodiEqui(toString(this.cmbCodiEqui.getSelectedIndex()));
            obje.setNombJuga(this.txtNombJuga.getText());
            obje.setEdadJuga(Integer.parseInt(this.txtEdad.getText()));
            obje.setAltuJuga(Double.parseDouble(this.txtAltu.getText()));
            obje.setPesoJuga(Double.parseDouble(this.txtPeso.getText()));

            if(new JugadoresCtrl().modi(obje))
            {
                JOptionPane.showMessageDialog(this, "Datos Modificados");
                MostrarJuga();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        btnGuardar1.setEnabled(true);
        btnModificar1.setEnabled(false);
        btnEliminar1.setEnabled(false);
        btnNuevo1.setEnabled(false);
        txtCodi1.setText("1");
        txtNombJuga.setText("");
        txtEdad.setText("");
        txtAltu.setText("");
        txtPeso.setText("");
        llenarCombobox();
        tblJugadores.clearSelection();
        DefaultTableModel model = (DefaultTableModel)this.tblJugadores.getModel();
        while (model.getRowCount()>0){model.removeRow(0);}
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        try
        {
            Jugadores obje = new Jugadores();
            obje.setCodiJuga(Integer.parseInt(this.txtCodi1.getText()));

            if(new JugadoresCtrl().elim(obje))
            {
                JOptionPane.showMessageDialog(this, "Datos Eliminados");
                MostrarJuga();
                txtCodi1.setText("1");
                txtNombJuga.setText("");
                txtEdad.setText("");
                txtAltu.setText("");
                txtPeso.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
        btnGuardar1.setEnabled(false);
        btnNuevo1.setEnabled(true);
        btnModificar1.setEnabled(true);
        btnEliminar1.setEnabled(true);
        MostrarJuga();
        llenarCombobox();
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    private void txtNombJugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombJugaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombJugaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try
        {
            Equipos obje = new Equipos();
            obje.setCodiEqui(Integer.parseInt(this.txtCodi.getText()));

            if(new EquiposCtrl().elim(obje))
            {
                JOptionPane.showMessageDialog(this, "Datos Eliminados");
                Mostrar();
                txtCodi.setText("");
                txtNomb.setText("");
                txtDesc.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnNuevo.setEnabled(false);
        txtCodi.setText("1");
        txtNomb.setText("");
        txtDesc.setText("");
        tblEquipos.clearSelection();
        DefaultTableModel model = (DefaultTableModel)this.tblEquipos.getModel();
        while (model.getRowCount()>0){model.removeRow(0);}

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try
        {
            Equipos obje = new Equipos();
            obje.setCodiEqui(Integer.parseInt(this.txtCodi.getText()));
            obje.setNombEqui(this.txtNomb.getText());
            obje.setDescEqui(this.txtDesc.getText());

            if(new EquiposCtrl().modi(obje))
            {
                JOptionPane.showMessageDialog(this, "Datos Modificados");
                Mostrar();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEquiposMouseClicked
        int fila = this.tblEquipos.getSelectedRow();
        if(fila >= 0)
        {
            Equipos obje = (Equipos)this.tblEquipos.getValueAt(fila, 0);
            this.txtCodi.setText(String.valueOf(obje.getCodiEqui()));
            this.txtNomb.setText(obje.getNombEqui());
            this.txtDesc.setText(obje.getDescEqui());
        }
    }//GEN-LAST:event_tblEquiposMouseClicked

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        Mostrar();

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try
        {
            if(txtNomb.getText().length()!=0 && txtDesc.getText().length()!=0)
            {
                Equipos obje = new Equipos();
                obje.setCodiEqui(Integer.parseInt(this.txtCodi.getText()));
                obje.setNombEqui(this.txtNomb.getText());
                obje.setDescEqui(this.txtDesc.getText());

                if(new EquiposCtrl().guar(obje))
                {
                    JOptionPane.showMessageDialog(this, "Datos guardados");
                    txtNomb.setText("");
                    txtDesc.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No deje campos vacios");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPartActionPerformed
        btnGuardarPart.setEnabled(false);
        btnNuevoPart.setEnabled(true);
        btnModificarPart.setEnabled(true);
        btnEliminarPart.setEnabled(true);
        MostrarPart();
        llenarCombobox();
    }//GEN-LAST:event_btnConsultarPartActionPerformed

    private void btnEliminarPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPartActionPerformed
         try
        {
            Partidos obje = new Partidos();
            obje.setCodiPart(Integer.parseInt(this.txtCodiPart.getText()));

            if(new PartidosCtrl().elim(obje))
            {
                JOptionPane.showMessageDialog(this, "Datos Eliminados");
                MostrarPart();
                txtCodiPart.setText("1");
                txtMarcEqui1.setText("");
                txtMarcEqui2.setText("");
                txtFechHora.setText("");
                txtLuga.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btnEliminarPartActionPerformed

    private void btnNuevoPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPartActionPerformed
        btnGuardarPart.setEnabled(true);
        btnModificarPart.setEnabled(false);
        btnEliminarPart.setEnabled(false);
        btnNuevoPart.setEnabled(false);
        txtCodiPart.setText("1");
        txtMarcEqui1.setText("");
        txtMarcEqui2.setText("");
        txtFechHora.setText("");
        txtLuga.setText("");
        llenarCombobox();
        tblPartidos.clearSelection();
        DefaultTableModel model = (DefaultTableModel)this.tblPartidos.getModel();
        while (model.getRowCount()>0){model.removeRow(0);}
    }//GEN-LAST:event_btnNuevoPartActionPerformed

    private void btnModificarPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPartActionPerformed
        try
        {
            Equipos objeEqu1 = (Equipos) this.cmbCodiEquiPart1.getSelectedItem();
                Equipos objeEqu2 = (Equipos) this.cmbCodiEquiPart2.getSelectedItem();
                Partidos obje = new Partidos();
                obje.setCodiPart(Integer.parseInt(this.txtCodiPart.getText()));
                obje.setCodiEqui1(objeEqu1.getCodiEqui());
                obje.setCodiEqui2(objeEqu2.getCodiEqui());
                obje.setGoleEqui1(Integer.parseInt(this.txtMarcEqui1.getText()));
                obje.setGoleEqui2(Integer.parseInt(this.txtMarcEqui2.getText()));
                obje.setFechHora(this.txtFechHora.getText());
                obje.setLugar(this.txtLuga.getText());

            if(new PartidosCtrl().modi(obje))
            {
                JOptionPane.showMessageDialog(this, "Datos Modificados");
                MostrarPart();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }





    }//GEN-LAST:event_btnModificarPartActionPerformed

    private void btnGuardarPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPartActionPerformed
        try {
            if(txtMarcEqui1.getText().length()!=0 && txtMarcEqui2.getText().length()!=0 && txtFechHora.getText().length()!=0)
            {
               
                Equipos objeEqu1 = (Equipos) this.cmbCodiEquiPart1.getSelectedItem();
                Equipos objeEqu2 = (Equipos) this.cmbCodiEquiPart2.getSelectedItem();
                Partidos obje = new Partidos();
                obje.setCodiPart(Integer.parseInt(this.txtCodiPart.getText()));
                obje.setCodiEqui1(objeEqu1.getCodiEqui());
                obje.setCodiEqui2(objeEqu2.getCodiEqui());
                obje.setGoleEqui1(Integer.parseInt(this.txtMarcEqui1.getText()));
                obje.setGoleEqui2(Integer.parseInt(this.txtMarcEqui2.getText()));
                obje.setFechHora(this.txtFechHora.getText());
                obje.setLugar(this.txtLuga.getText());
                
                if(new PartidosCtrl().guar(obje))
                {
                    JOptionPane.showMessageDialog(this, "Datos guardados");
                    txtCodiPart.setText("1");
                    txtMarcEqui1.setText("");
                    txtMarcEqui2.setText("");
                    txtFechHora.setText("");
                    txtLuga.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Oops! algo salio mal");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No deje campos vacios");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }




    }//GEN-LAST:event_btnGuardarPartActionPerformed

    private void tblPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPartidosMouseClicked
                try{
            int fila = this.tblPartidos.getSelectedRow();
            if(fila >= 0)
            {
                Partidos obje = (Partidos)this.tblPartidos.getValueAt(fila, 3);
                this.txtCodiPart.setText(String.valueOf(obje.getCodiPart()));
                this.cmbCodiEquiPart1.setEditable(true);
                this.cmbCodiEquiPart1.setSelectedItem((Equipos)new EquiposCtrl().concmb(obje.getCodiEqui1()));
                this.cmbCodiEquiPart1.setEditable(false);
                this.cmbCodiEquiPart2.setEditable(true);
                this.cmbCodiEquiPart2.setSelectedItem((Equipos)new EquiposCtrl().concmb(obje.getCodiEqui2()));
                this.cmbCodiEquiPart2.setEditable(false);
                this.txtMarcEqui1.setText(String.valueOf(obje.getGoleEqui1()));
                this.txtMarcEqui2.setText(String.valueOf(obje.getGoleEqui2()));
                this.txtFechHora.setText(obje.getFechHora());
                this.txtLuga.setText(obje.getLugar());
            }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Error"+ ex.getMessage());
            }
    }//GEN-LAST:event_tblPartidosMouseClicked

    private void cmbCodiEquiPart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodiEquiPart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCodiEquiPart1ActionPerformed

    private void txtMarcEqui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcEqui1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcEqui1ActionPerformed

    private void tblPartidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPartidosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPartidosMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnConsultarPart;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminarPart;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardarPart;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnModificarPart;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnNuevoPart;
    private javax.swing.JComboBox cmbCodiEqui;
    private javax.swing.JComboBox cmbCodiEquiPart1;
    private javax.swing.JComboBox cmbCodiEquiPart2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblEquipos;
    private javax.swing.JTable tblJugadores;
    private javax.swing.JTable tblPartidos;
    private javax.swing.JTextField txtAltu;
    private javax.swing.JTextField txtCodi;
    private javax.swing.JTextField txtCodi1;
    private javax.swing.JTextField txtCodiPart;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechHora;
    private javax.swing.JTextField txtLuga;
    private javax.swing.JTextField txtMarcEqui1;
    private javax.swing.JTextField txtMarcEqui2;
    private javax.swing.JTextField txtNomb;
    private javax.swing.JTextField txtNombJuga;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
